### ISSUE TITLE
How to generate SAE client certificates?

### ISSUE THREAD

**Issue by krns636** [next-door-key/qkd-trusted-node#2]
Once the certificates for all KMEs are generated, the QKD simulated links are running, and each of the 4 Trusted Nodes is in execution. There is no SAE-A.crt and SAE-B.crt in the certs folder to start sending requests to the TN ETSI-014 APIs for keys or status. How can we generate those?

Thank you, and congratulations on your huge work!

**Comment by CreepPork** [comment]
Hi!

Thank you for your kind words.

These SAE certs are not included by default, by the script, because I assumed that they would be provided by the configurator.

If you want to create these certificates, you can take as a starting guide the shell script and fill out the variables.

But for convenience, here is the shell script to create it for SAE A. To create it for SAE B just replace everything that mentions `sae-a` to `sae-b`.

```bash
cd ./certs
openssl req -new -nodes -out sae-a.csr -newkey rsa:4096 -keyout sae-a.key -subj "/CN=sae-a/O=SAE 1/C=LV"
openssl x509 -req -in sae-a.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out sae-a.crt -days 365 -sha256
```
